# Generated by Django 5.2.11 on 2026-02-16 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_product_review'),
    ]

    operations = [
        # This migration is now redundant because 0001_initial.py creates Cart with UUID
    ]
