version: "3.9"
services:
  web:
    build:
      context: .
    volumes:
      - .:/app                     
    env_file:
      - backend.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network

  db:
    image: mysql:8.1
    restart: always
    networks:
      - shared-network
    env_file:
      - db.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} || exit 1"]
      interval: 5s
      retries: 10
      timeout: 5s
    ports:
      - "3306:3306"

  test:
    build:
      context: .
    depends_on:
      web:
        condition: service_started
    volumes:
      - .:/app
    command: pytest
    networks:
      - shared-network

volumes:
  mysql_data:


networks:
  shared-network:
    external: true